spring.application.name=mini-erp-backend
server.port=${PORT:8080}

# Database Configuration (Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Security
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
